### ISSUE TITLE
Add middleware to endpoint 

### ISSUE THREAD

**Issue by jeandersoncruz** [FilledStacks/firebase-backend#108]
Would be nice if we could pass as optional value an **_array_** of middlewares/handler to validate things like authentication, role, and etc...

**Describe the solution you'd like**
signature some like this:
```
export default new Post([
 //Middleware 1 (express.Request, express.Response, express.NextFunction)
        isAuthenticated,
 //Middleware 2 (express.Request, express.Response, express.NextFunction)
        isAuthorized({ hasRole: ['admin', 'manager'] }),
// Any other middleware necessary (express.Request, express.Response, express.NextFunction)
       [...]
//(express.Request, express.Response)
        handler]);
```
**Additional context**
This adds the ability to control when an endpoint needs access control.

You can check this repo to better understanding.
https://github.com/joaqcid/firebase-user-role-api/tree/master

**Comment by verygreenboi** [comment]
@jeandersoncruz I've made a fork of this project and implemented middleware support. You can check it out pending if my PR gets merged.

**Comment by FilledStacks** [comment]
Merged sorry @verygreenboi for taking so long

**Comment by FilledStacks** [comment]
I'll release a new version as well.

**Comment by Mood93** [comment]
Can this issue be closed?

**Comment by FilledStacks** [comment]
Yes @Mood93
