### ISSUE TITLE
Add callable functions

### ISSUE THREAD

**Issue by uppergoal** [FilledStacks/firebase-backend#25]
Adding callable functions to the code structure.

**Comment by fransiskapw** [comment]
+1 This is the main reason that made me unsure about using the package

**Comment by FilledStacks** [comment]
@uppergoal We'll have to create another function type called callable?

So we'll add functionality to check on filename `.callable.js` which will then get together all callable functions per resource and deploy it to the same group. 

I don't have dev available at the moment that can tackle this functionality but will add it to the board.

**Comment by MaxAuer** [comment]
Short term solution: 

You can just add the callable function to the index.ts
```
import { FunctionParser } from "firebase-backend";
import * as functions from 'firebase-functions';

exports = new FunctionParser(__dirname, exports).exports;

exports.functionCall = functions.https.onCall((data, context) => {
    const uid = context.auth?.uid;
    console.log(`Request for ${uid}`);

    return { 'success': true }
});
```

This will deploy the function and you can use it as usual.

**Comment by fransiskapw** [comment]
In addition to the callable function, would also be nice to include schedulers as well 
https://firebase.google.com/docs/functions/schedule-functions

**Comment by MaxAuer** [comment]
@fransiskapw @FilledStacks 
For schedule functions: any ideas on function type name?
`.schedulable` seems a bit strange. But maybe that's just me.

**Comment by FilledStacks** [comment]
haha @MaxAuer it's definitely strange. I think we can go with `.schedule` . Or `.scheduled` I think the first one reads better. 

`sendWeeklyReport.schedule.ts` says exactly what it is. 

`cleanMediaCache.schedule.ts` as well. 

I thin that would work well. 

also thanks so much for #26 I will review soon and merge in for a new release.

**Comment by FilledStacks** [comment]
We've decided that the code change was not required. We will update the readme to explain how to use callable functions.

**Comment by uppergoal** [comment]
Thanks @fransiskapw and @MaxAuer. I'll read the doc and follow your guidelines.
