### ISSUE TITLE
Http request deploy region

### ISSUE THREAD

**Issue by harsh04** [FilledStacks/firebase-backend#43]
How to set the region of function triggered by http endpoint. I was able to do it for event driven function but unable to get it work for http callable function

**Comment by FilledStacks** [comment]
@harsh04 for a callable function it'll work the same as you would normally do it. a callable funcion is defined the same as a reactive function. The folder you put it in is just called `callable/myCallableFunction.function.ts` Then it'll be added and exported as normal.

**Comment by samiulhsohan** [comment]
@harsh04 Can you please tell me how did you set a region for event-driven functions?

**Comment by harsh04** [comment]
> @harsh04 Can you please tell me how did you set a region for event-driven functions?

```
exports.updateUserProfile = functions.region("asia-south1").firestore.document("users/{userId}").onWrite(async (change, context) => {
    // perform required actions
});
```
