### ISSUE TITLE
Please add functions.runWith option

### ISSUE THREAD

**Issue by vincenttan83** [FilledStacks/firebase-backend#9]
We have few functions that required longer run time and more memory allocation.

**Comment by adamschnaare** [comment]
@vincenttan83 , I'm unfamiliar with the usage in this scenario. The codebase already supports customizing reactive firebase functions. You just need to author them as such (from what I can tell):

```js
export default functions
.runWith({...})
.firestore
  .document("users/{userId}")
  .onCreate((usersSnapshot, context) => {
    ...
  });
```

My question is with the `onRequest` method. Would the following be an example of how you would expect to use it?
```js
const app = express(); // your app and request handlers, etc...
functions.runWith({...}).https.onRequest(app)
```

**Comment by vincenttan83** [comment]
Yes, both onRequest, and reative, e.g.:
```js
exports.someFunction = functions
    .runWith({
        timeoutSeconds: 540,
        memory: '2GB'
    })
    .firestore
    .document('some_collection/some_doc')
    .onUpdate(async (snapshot, context) => {

```

**Comment by FilledStacks** [comment]
@vincenttan83 PR is in review. Thanks for the issue.
